### ISSUE TITLE
'float' object has no attribute 'get'

### ISSUE THREAD

**Issue by Local9** [HubbleStack/Nebula#32]
```
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1412, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\var\cache\salt\minion\extmods\modules\nebula_osquery.py", line 104, in queries
        'data': [{'uptime': __salt__['status.uptime']().get('seconds', __salt__['cmd.run']('uptime'))}],
    AttributeError: 'float' object has no attribute 'get'
```

Message above is returned when trying to get nebula.queries day from a windows machine.

**Comment by basepi** [comment]
Thanks for the report, we'll modify that fallback query so that it works on windows as well.
